### ISSUE TITLE
wasm support

### ISSUE THREAD

**Issue by databasedav** [rowan-sl/coqui-rs#1]
will this work in wasm? ideally i would want to be able to fetch voice models remotely, and use them to play tts through the browser

**Comment by ashsystems** [comment]
Unfortunately this will probably never be able to work in the browser (at least not with out a LOT of work) since it is bindings to a python library. Also the compute power required to run this is far beyond what is provided by most wasm environments. (and client's devices)

If you do want to make a website to do TTS I recommend either using a web API ([google has one](https://codelabs.developers.google.com/codelabs/cloud-text-speech-python3/#0)) or making requests to a server that runs the TTS model.
